// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data.Configurations;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agendamento> Agendamento { get; set; }

    public virtual DbSet<Atendimento> Atendimento { get; set; }

    public virtual DbSet<Cidade> Cidade { get; set; }

    public virtual DbSet<Clinica> Clinica { get; set; }

    public virtual DbSet<Especialidade> Especialidade { get; set; }

    public virtual DbSet<EspecialidadeMedico> EspecialidadeMedico { get; set; }

    public virtual DbSet<Uf> Uf { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.ApplyConfiguration(new Configurations.AgendamentoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AtendimentoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CidadeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClinicaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EspecialidadeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EspecialidadeMedicoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UfConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuarioConfiguration());
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
