// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Agendamento
{
    public int PkAgendamento { get; set; }

    public int FkUsuarioPaciente { get; set; }

    public int FkUsuarioMedico { get; set; }

    public DateOnly? Cancelamento { get; set; }

    public DateTime? DtConsulta { get; set; }

    public DateTime? DtSolicitacao { get; set; }

    public virtual Atendimento Atendimento { get; set; }

    public virtual Usuario FkUsuarioMedicoNavigation { get; set; }

    public virtual Usuario FkUsuarioPacienteNavigation { get; set; }
}
