// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Atendimento
{
    public int PkAtendimento { get; set; }

    public int FkAgendamento { get; set; }

    public int FkUsuarioPaciente { get; set; }

    public string Receita { get; set; }

    public string Diagnostico { get; set; }

    public short? NotaAtendimento { get; set; }

    public string ObseracoesPaciente { get; set; }

    public string ObservacoesMedico { get; set; }

    public int FkUsuarioMedico { get; set; }

    public short Status { get; set; }

    public virtual Agendamento FkAgendamentoNavigation { get; set; }

    public virtual Usuario FkUsuarioMedicoNavigation { get; set; }

    public virtual Usuario FkUsuarioPacienteNavigation { get; set; }
}
