// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Cidade
{
    public int PkCidade { get; set; }

    public string Nome { get; set; }

    public string Uf { get; set; }

    public int? Codigo { get; set; }

    public virtual ICollection<Clinica> Clinica { get; set; } = new List<Clinica>();

    public virtual Uf UfNavigation { get; set; }

    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}
