// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjetoClinica.Domain.Entities;

public partial class clinicaprojectContext : DbContext
{
    public clinicaprojectContext(DbContextOptions<clinicaprojectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agendamento> Agendamento { get; set; }

    public virtual DbSet<Atendimento> Atendimento { get; set; }

    public virtual DbSet<Cidade> Cidade { get; set; }

    public virtual DbSet<Clinica> Clinica { get; set; }

    public virtual DbSet<Especialidade> Especialidade { get; set; }

    public virtual DbSet<EspecialidadeMedico> EspecialidadeMedico { get; set; }

    public virtual DbSet<Uf> Uf { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Agendamento>(entity =>
        {
            entity.HasKey(e => e.PkAgendamento).HasName("PRIMARY");

            entity
                .ToTable("agendamento")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.HasIndex(e => e.FkUsuarioPaciente, "FK_USUARIO_PACIENTE");

            entity.Property(e => e.PkAgendamento).HasColumnName("PK_AGENDAMENTO");
            entity.Property(e => e.Cancelamento).HasColumnName("cancelamento");
            entity.Property(e => e.DtConsulta)
                .HasColumnType("datetime")
                .HasColumnName("DT_CONSULTA");
            entity.Property(e => e.DtSolicitacao)
                .HasColumnType("datetime")
                .HasColumnName("DT_SOLICITACAO");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");
            entity.Property(e => e.FkUsuarioPaciente).HasColumnName("FK_USUARIO_PACIENTE");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.AgendamentoFkUsuarioMedicoNavigation)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("agendamento_ibfk_2");

            entity.HasOne(d => d.FkUsuarioPacienteNavigation).WithMany(p => p.AgendamentoFkUsuarioPacienteNavigation)
                .HasForeignKey(d => d.FkUsuarioPaciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("agendamento_ibfk_1");
        });

        modelBuilder.Entity<Atendimento>(entity =>
        {
            entity.HasKey(e => e.PkAtendimento).HasName("PRIMARY");

            entity
                .ToTable("atendimento")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkAgendamento, "FK_AGENDAMENTO").IsUnique();

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.HasIndex(e => e.FkUsuarioPaciente, "FK_USUARIO_PACIENTE");

            entity.HasIndex(e => new { e.PkAtendimento, e.FkAgendamento }, "PK_ATENDIMENTO").IsUnique();

            entity.Property(e => e.PkAtendimento)
                .ValueGeneratedNever()
                .HasColumnName("PK_ATENDIMENTO");
            entity.Property(e => e.Diagnostico)
                .HasMaxLength(255)
                .HasColumnName("DIAGNOSTICO");
            entity.Property(e => e.FkAgendamento).HasColumnName("FK_AGENDAMENTO");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");
            entity.Property(e => e.FkUsuarioPaciente).HasColumnName("FK_USUARIO_PACIENTE");
            entity.Property(e => e.NotaAtendimento).HasColumnName("NOTA_ATENDIMENTO");
            entity.Property(e => e.ObseracoesPaciente)
                .HasMaxLength(255)
                .HasColumnName("OBSERACOES_PACIENTE");
            entity.Property(e => e.ObservacoesMedico)
                .HasMaxLength(255)
                .HasColumnName("OBSERVACOES_MEDICO");
            entity.Property(e => e.Receita)
                .HasMaxLength(255)
                .HasColumnName("RECEITA");
            entity.Property(e => e.Status).HasColumnName("status");

            entity.HasOne(d => d.FkAgendamentoNavigation).WithOne(p => p.Atendimento)
                .HasForeignKey<Atendimento>(d => d.FkAgendamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_1");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.AtendimentoFkUsuarioMedicoNavigation)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_3");

            entity.HasOne(d => d.FkUsuarioPacienteNavigation).WithMany(p => p.AtendimentoFkUsuarioPacienteNavigation)
                .HasForeignKey(d => d.FkUsuarioPaciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_2");
        });

        modelBuilder.Entity<Cidade>(entity =>
        {
            entity.HasKey(e => e.PkCidade).HasName("PRIMARY");

            entity
                .ToTable("cidade")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.Uf, "UF");

            entity.Property(e => e.PkCidade).HasColumnName("PK_CIDADE");
            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("NOME");
            entity.Property(e => e.Uf)
                .IsRequired()
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("UF");

            entity.HasOne(d => d.UfNavigation).WithMany(p => p.Cidade)
                .HasForeignKey(d => d.Uf)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cidade_ibfk_1");
        });

        modelBuilder.Entity<Clinica>(entity =>
        {
            entity.HasKey(e => e.PkClinica).HasName("PRIMARY");

            entity
                .ToTable("clinica")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkCidade, "FK_CIDADE");

            entity.Property(e => e.PkClinica).HasColumnName("PK_CLINICA");
            entity.Property(e => e.Cnpj)
                .HasMaxLength(14)
                .IsFixedLength()
                .HasColumnName("CNPJ");
            entity.Property(e => e.Endereco)
                .IsRequired()
                .HasMaxLength(90)
                .HasColumnName("ENDERECO");
            entity.Property(e => e.FkCidade).HasColumnName("FK_CIDADE");
            entity.Property(e => e.Nome)
                .HasMaxLength(45)
                .HasColumnName("NOME");
            entity.Property(e => e.Telefone)
                .HasMaxLength(45)
                .HasColumnName("TELEFONE");

            entity.HasOne(d => d.FkCidadeNavigation).WithMany(p => p.Clinica)
                .HasForeignKey(d => d.FkCidade)
                .HasConstraintName("clinica_ibfk_1");
        });

        modelBuilder.Entity<Especialidade>(entity =>
        {
            entity.HasKey(e => e.PkEspecialidade).HasName("PRIMARY");

            entity
                .ToTable("especialidade")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.Property(e => e.PkEspecialidade).HasColumnName("PK_ESPECIALIDADE");
            entity.Property(e => e.NomeEspecialidade)
                .IsRequired()
                .HasMaxLength(90)
                .HasColumnName("NOME_ESPECIALIDADE");
        });

        modelBuilder.Entity<EspecialidadeMedico>(entity =>
        {
            entity.HasKey(e => e.PkEspecialidadeMedicoEspecialidade).HasName("PRIMARY");

            entity
                .ToTable("especialidade_medico")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkEspecialidade, "FK_ESPECIALIDADE");

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.Property(e => e.PkEspecialidadeMedicoEspecialidade)
                .ValueGeneratedNever()
                .HasColumnName("PK_ESPECIALIDADE_MEDICO_ESPECIALIDADE");
            entity.Property(e => e.FkEspecialidade).HasColumnName("FK_ESPECIALIDADE");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");

            entity.HasOne(d => d.FkEspecialidadeNavigation).WithMany(p => p.EspecialidadeMedico)
                .HasForeignKey(d => d.FkEspecialidade)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("especialidade_medico_ibfk_1");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.EspecialidadeMedico)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("especialidade_medico_ibfk_2");
        });

        modelBuilder.Entity<Uf>(entity =>
        {
            entity.HasKey(e => e.Uf1).HasName("PRIMARY");

            entity
                .ToTable("uf")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.Property(e => e.Uf1)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("UF");
            entity.Property(e => e.Codigouf).HasColumnName("CODIGOUF");
            entity.Property(e => e.Nome)
                .HasMaxLength(50)
                .HasColumnName("NOME");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.PkUsuario).HasName("PRIMARY");

            entity
                .ToTable("usuario")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.Cpf, "CPF").IsUnique();

            entity.HasIndex(e => e.Email, "EMAIL").IsUnique();

            entity.HasIndex(e => e.FkCidade, "FK_CIDADE");

            entity.Property(e => e.PkUsuario).HasColumnName("PK_USUARIO");
            entity.Property(e => e.Cpf)
                .HasMaxLength(11)
                .IsFixedLength()
                .HasColumnName("CPF");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("EMAIL");
            entity.Property(e => e.FkCidade).HasColumnName("FK_CIDADE");
            entity.Property(e => e.NomeUsuario)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("NOME_USUARIO");
            entity.Property(e => e.Telefone)
                .HasMaxLength(9)
                .HasColumnName("TELEFONE");
            entity.Property(e => e.Tipo).HasColumnName("TIPO");

            entity.HasOne(d => d.FkCidadeNavigation).WithMany(p => p.Usuario)
                .HasForeignKey(d => d.FkCidade)
                .HasConstraintName("usuario_ibfk_1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
