// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Clinica
{
    public int PkClinica { get; set; }

    public string Nome { get; set; }

    public string Telefone { get; set; }

    public string Endereco { get; set; }

    public int? FkCidade { get; set; }

    public string Cnpj { get; set; }

    public virtual Cidade FkCidadeNavigation { get; set; }
}
