// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Especialidade
{
    public int PkEspecialidade { get; set; }

    public string NomeEspecialidade { get; set; }

    public virtual ICollection<EspecialidadeMedico> EspecialidadeMedico { get; set; } = new List<EspecialidadeMedico>();
}
