// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class EspecialidadeMedico
{
    public int PkEspecialidadeMedicoEspecialidade { get; set; }

    public int FkEspecialidade { get; set; }

    public int FkUsuarioMedico { get; set; }

    public virtual Especialidade FkEspecialidadeNavigation { get; set; }

    public virtual Usuario FkUsuarioMedicoNavigation { get; set; }
}
