// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Uf
{
    public string Uf1 { get; set; }

    public int? Codigouf { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Cidade> Cidade { get; set; } = new List<Cidade>();
}
