// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;

namespace ProjetoClinica.Domain.Entities;

public partial class Usuario
{
    public int PkUsuario { get; set; }

    public string NomeUsuario { get; set; }

    public short Tipo { get; set; }

    public string Telefone { get; set; }

    public string Email { get; set; }

    public string Cpf { get; set; }

    public int? FkCidade { get; set; }

    public virtual ICollection<Agendamento> AgendamentoFkUsuarioMedicoNavigation { get; set; } = new List<Agendamento>();

    public virtual ICollection<Agendamento> AgendamentoFkUsuarioPacienteNavigation { get; set; } = new List<Agendamento>();

    public virtual ICollection<Atendimento> AtendimentoFkUsuarioMedicoNavigation { get; set; } = new List<Atendimento>();

    public virtual ICollection<Atendimento> AtendimentoFkUsuarioPacienteNavigation { get; set; } = new List<Atendimento>();

    public virtual ICollection<EspecialidadeMedico> EspecialidadeMedico { get; set; } = new List<EspecialidadeMedico>();

    public virtual Cidade FkCidadeNavigation { get; set; }
}
