// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class AgendamentoConfiguration : IEntityTypeConfiguration<Agendamento>
    {
        public void Configure(EntityTypeBuilder<Agendamento> entity)
        {
            entity.HasKey(e => e.PkAgendamento).HasName("PRIMARY");

            entity
                .ToTable("agendamento")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.HasIndex(e => e.FkUsuarioPaciente, "FK_USUARIO_PACIENTE");

            entity.Property(e => e.PkAgendamento).HasColumnName("PK_AGENDAMENTO");
            entity.Property(e => e.Cancelamento).HasColumnName("cancelamento");
            entity.Property(e => e.DtConsulta)
                .HasColumnType("datetime")
                .HasColumnName("DT_CONSULTA");
            entity.Property(e => e.DtSolicitacao)
                .HasColumnType("datetime")
                .HasColumnName("DT_SOLICITACAO");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");
            entity.Property(e => e.FkUsuarioPaciente).HasColumnName("FK_USUARIO_PACIENTE");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.AgendamentoFkUsuarioMedicoNavigation)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("agendamento_ibfk_2");

            entity.HasOne(d => d.FkUsuarioPacienteNavigation).WithMany(p => p.AgendamentoFkUsuarioPacienteNavigation)
                .HasForeignKey(d => d.FkUsuarioPaciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("agendamento_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Agendamento> entity);
    }
}
