// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class AtendimentoConfiguration : IEntityTypeConfiguration<Atendimento>
    {
        public void Configure(EntityTypeBuilder<Atendimento> entity)
        {
            entity.HasKey(e => e.PkAtendimento).HasName("PRIMARY");

            entity
                .ToTable("atendimento")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkAgendamento, "FK_AGENDAMENTO").IsUnique();

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.HasIndex(e => e.FkUsuarioPaciente, "FK_USUARIO_PACIENTE");

            entity.HasIndex(e => new { e.PkAtendimento, e.FkAgendamento }, "PK_ATENDIMENTO").IsUnique();

            entity.Property(e => e.PkAtendimento)
                .ValueGeneratedNever()
                .HasColumnName("PK_ATENDIMENTO");
            entity.Property(e => e.Diagnostico)
                .HasMaxLength(255)
                .HasColumnName("DIAGNOSTICO");
            entity.Property(e => e.FkAgendamento).HasColumnName("FK_AGENDAMENTO");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");
            entity.Property(e => e.FkUsuarioPaciente).HasColumnName("FK_USUARIO_PACIENTE");
            entity.Property(e => e.NotaAtendimento).HasColumnName("NOTA_ATENDIMENTO");
            entity.Property(e => e.ObseracoesPaciente)
                .HasMaxLength(255)
                .HasColumnName("OBSERACOES_PACIENTE");
            entity.Property(e => e.ObservacoesMedico)
                .HasMaxLength(255)
                .HasColumnName("OBSERVACOES_MEDICO");
            entity.Property(e => e.Receita)
                .HasMaxLength(255)
                .HasColumnName("RECEITA");
            entity.Property(e => e.Status).HasColumnName("status");

            entity.HasOne(d => d.FkAgendamentoNavigation).WithOne(p => p.Atendimento)
                .HasForeignKey<Atendimento>(d => d.FkAgendamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_1");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.AtendimentoFkUsuarioMedicoNavigation)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_3");

            entity.HasOne(d => d.FkUsuarioPacienteNavigation).WithMany(p => p.AtendimentoFkUsuarioPacienteNavigation)
                .HasForeignKey(d => d.FkUsuarioPaciente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("atendimento_ibfk_2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Atendimento> entity);
    }
}
