// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class CidadeConfiguration : IEntityTypeConfiguration<Cidade>
    {
        public void Configure(EntityTypeBuilder<Cidade> entity)
        {
            entity.HasKey(e => e.PkCidade).HasName("PRIMARY");

            entity
                .ToTable("cidade")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.Uf, "UF");

            entity.Property(e => e.PkCidade).HasColumnName("PK_CIDADE");
            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("NOME");
            entity.Property(e => e.Uf)
                .IsRequired()
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("UF");

            entity.HasOne(d => d.UfNavigation).WithMany(p => p.Cidade)
                .HasForeignKey(d => d.Uf)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("cidade_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Cidade> entity);
    }
}
