// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class ClinicaConfiguration : IEntityTypeConfiguration<Clinica>
    {
        public void Configure(EntityTypeBuilder<Clinica> entity)
        {
            entity.HasKey(e => e.PkClinica).HasName("PRIMARY");

            entity
                .ToTable("clinica")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkCidade, "FK_CIDADE");

            entity.Property(e => e.PkClinica).HasColumnName("PK_CLINICA");
            entity.Property(e => e.Cnpj)
                .HasMaxLength(14)
                .IsFixedLength()
                .HasColumnName("CNPJ");
            entity.Property(e => e.Endereco)
                .IsRequired()
                .HasMaxLength(90)
                .HasColumnName("ENDERECO");
            entity.Property(e => e.FkCidade).HasColumnName("FK_CIDADE");
            entity.Property(e => e.Nome)
                .HasMaxLength(45)
                .HasColumnName("NOME");
            entity.Property(e => e.Telefone)
                .HasMaxLength(45)
                .HasColumnName("TELEFONE");

            entity.HasOne(d => d.FkCidadeNavigation).WithMany(p => p.Clinica)
                .HasForeignKey(d => d.FkCidade)
                .HasConstraintName("clinica_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Clinica> entity);
    }
}
