// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class EspecialidadeMedicoConfiguration : IEntityTypeConfiguration<EspecialidadeMedico>
    {
        public void Configure(EntityTypeBuilder<EspecialidadeMedico> entity)
        {
            entity.HasKey(e => e.PkEspecialidadeMedicoEspecialidade).HasName("PRIMARY");

            entity
                .ToTable("especialidade_medico")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.FkEspecialidade, "FK_ESPECIALIDADE");

            entity.HasIndex(e => e.FkUsuarioMedico, "FK_USUARIO_MEDICO");

            entity.Property(e => e.PkEspecialidadeMedicoEspecialidade)
                .ValueGeneratedNever()
                .HasColumnName("PK_ESPECIALIDADE_MEDICO_ESPECIALIDADE");
            entity.Property(e => e.FkEspecialidade).HasColumnName("FK_ESPECIALIDADE");
            entity.Property(e => e.FkUsuarioMedico).HasColumnName("FK_USUARIO_MEDICO");

            entity.HasOne(d => d.FkEspecialidadeNavigation).WithMany(p => p.EspecialidadeMedico)
                .HasForeignKey(d => d.FkEspecialidade)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("especialidade_medico_ibfk_1");

            entity.HasOne(d => d.FkUsuarioMedicoNavigation).WithMany(p => p.EspecialidadeMedico)
                .HasForeignKey(d => d.FkUsuarioMedico)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("especialidade_medico_ibfk_2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EspecialidadeMedico> entity);
    }
}
