// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class EspecialidadeConfiguration : IEntityTypeConfiguration<Especialidade>
    {
        public void Configure(EntityTypeBuilder<Especialidade> entity)
        {
            entity.HasKey(e => e.PkEspecialidade).HasName("PRIMARY");

            entity
                .ToTable("especialidade")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.Property(e => e.PkEspecialidade).HasColumnName("PK_ESPECIALIDADE");
            entity.Property(e => e.NomeEspecialidade)
                .IsRequired()
                .HasMaxLength(90)
                .HasColumnName("NOME_ESPECIALIDADE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Especialidade> entity);
    }
}
