// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class UfConfiguration : IEntityTypeConfiguration<Uf>
    {
        public void Configure(EntityTypeBuilder<Uf> entity)
        {
            entity.HasKey(e => e.Uf1).HasName("PRIMARY");

            entity
                .ToTable("uf")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.Property(e => e.Uf1)
                .HasMaxLength(2)
                .IsFixedLength()
                .HasColumnName("UF");
            entity.Property(e => e.Codigouf).HasColumnName("CODIGOUF");
            entity.Property(e => e.Nome)
                .HasMaxLength(50)
                .HasColumnName("NOME");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Uf> entity);
    }
}
