// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProjetoClinica.Domain.Entities;
using ProjetoClinica.Infra.Data;
using System;
using System.Collections.Generic;

namespace ProjetoClinica.Infra.Data.Configurations
{
    public partial class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
    {
        public void Configure(EntityTypeBuilder<Usuario> entity)
        {
            entity.HasKey(e => e.PkUsuario).HasName("PRIMARY");

            entity
                .ToTable("usuario")
                .HasCharSet("utf8mb3")
                .UseCollation("utf8mb3_general_ci");

            entity.HasIndex(e => e.Cpf, "CPF").IsUnique();

            entity.HasIndex(e => e.Email, "EMAIL").IsUnique();

            entity.HasIndex(e => e.FkCidade, "FK_CIDADE");

            entity.Property(e => e.PkUsuario).HasColumnName("PK_USUARIO");
            entity.Property(e => e.Cpf)
                .HasMaxLength(11)
                .IsFixedLength()
                .HasColumnName("CPF");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("EMAIL");
            entity.Property(e => e.FkCidade).HasColumnName("FK_CIDADE");
            entity.Property(e => e.NomeUsuario)
                .IsRequired()
                .HasMaxLength(45)
                .HasColumnName("NOME_USUARIO");
            entity.Property(e => e.Telefone)
                .HasMaxLength(9)
                .HasColumnName("TELEFONE");
            entity.Property(e => e.Tipo).HasColumnName("TIPO");

            entity.HasOne(d => d.FkCidadeNavigation).WithMany(p => p.Usuario)
                .HasForeignKey(d => d.FkCidade)
                .HasConstraintName("usuario_ibfk_1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Usuario> entity);
    }
}
